<config.mk

all:V: bin/targets
	set -x
	mk creaBatch
	bin/targets | xargs mk

results/TRA.bcf: results/Batch00.bcf  results/Batch01.bcf results/Batch02.bcf  results/Batch03.bcf results/Batch04.bcf results/Batch05.bcf results/Batch06.bcf results/Batch07.bcf  results/Batch08.bcf results/Batch09.bcf results/Batch10.bcf results/Batch11.bcf
	bcftools merge -m id -O b -o $target $prereq

results/Batch%.bcf: data/Batch_clean%
	set -x
	mkdir -p `dirname $target`
	delly-parallel call -t $TOOL -g $REF -o $target".build" \
		 -v data/merge.bcf `cat $prereq` \
	&& mv $target".build" $target

data/Batch_clean%: data/Batch%
	set -x
	cat $prereq | tr "\n" " " > $target".build" \
	&& mv $target".build" $target

creaBatch:V: data/merge.bcf
	set -x
	ls data/bams/*.bam > out.txt
	split -l 8 out.txt -a 2 -d Batch \
	&& mv Batch* data/ \
	&& rm out.txt

