< config.mk

##Merge SV sites into a unified site list
results/%.merged.bcf:	results/%.call.bcf
	set -x
	mkdir -p `dirname $target`
	delly-parallel merge \
		-t $stem \
		-m $MIN_LONG \
		-n $MAX_LONG \
		-o $target.build \
		-b 500 \
		-r $OVERLAP \
		$prereq \
        && mv $target.build $target \
	&& mv $target.build.csi $target.csi #\
#	&& rm $prereq*

##SV calling using all samples in data/ 
results/%.call.bcf:
	set -x
	mkdir -p `dirname $target`
	delly-parallel call \
		-t $stem \
		-g $REF \
		-o $target.build \
		data/*.bam \
	&& mv $target.build $target \
	&& mv $target.build.csi $target.csi

clean:V:
	rm results/*.call.bcf*
