<config.mk

all:V: bin/targets
	set -x
	mk creaBatch
	bin/targets | xargs mk
	
results/Batch%.bcf: data/Batch_clean%
	set -x
	mkdir -p `dirname $target`
	delly-parallel call -t $TOOL -g $REF -o $target".build" \
		 `cat $prereq` \
	&& mv $target".build" $target

data/Batch_clean%: data/Batch%
	set -x
	cat $prereq | tr "\n" " " > $target".build" \
	&& mv $target".build" $target

creaBatch:V: 
	set -x
	ls data/bams/*.bam > out.txt
	split -l 8 out.txt -a 2 -d Batch \
	&& mv Batch* data/ \
	&& rm out.txt

