## DESCRIPTION:
## mk module Structural Variant (SV) bcf file joining and germline filtering using mk-delly pipeline.
## The script performs merging of multiple bcf files from SV calling into a single multisample bcf file; then, applies Delly2 germline filtering to keep only SV that pass the criteria of the filter.
##
## USAGE:
## Alternative 1: Single target execution.
##      mk results/<SV_TYPE>.delly_germline.bcf
##      where <SV_TYPE> must be: DEL, DUP, INV, TRA or INS.
##
##      example:
##      mk results/DEL.delly_germline.bcf
##
## Alternative 2: Multiple target tandem execution.
##      bin/targets | xargs mk
##
## Alternative 3: Multiple target parallel execution. NOTE: requires HTCondor.
##      condor submit
##
## AUTHOR:
##      Israel Aguilar (iaguilaror@gmail.com), for Winter Genomics (http://www.wintergenomics.com/), by request of INMEGEN (http://www.inmegen.gob.mx/) - 2017

< config.mk

#Apply the germline SV filter
results/%.delly_germline.bcf: results/%.merged.bcf
	set -x
	mkdir -p `dirname $target`
	delly-parallel filter \
	-t $stem \
	-m $MIN_LONG \
	-n $MAX_LONG \
	-f germline \
	-o $target.build \
	-p \
	$prereq \
	&& mv $target.build $target \
	&& mv $target.build.csi $target.csi

#Merge all re-genotyped samples to get a single VCF/BCF using bcftools merge
results/%.merged.bcf: data/%
	set -x
        mkdir -p `dirname $target`
	bcftools merge \
	-m id \
	-O b \
	-o $target.build \
	$prereq/*.bcf \
	&& mv $target.build $target \
	&& bcftools index -f $target

clean:V:
	rm results/*.merged.bcf*
