< ../config.mk

all:VQ: bin/targets
##	set -x
	mk creaBatch
	bin/targets | xargs mk
	
results/Batch%.bcf:Q: tmp/Batch_clean%
##	set -x
	mkdir -p `dirname $target`
	TOOL=$(pwd | tr "/" "\n" | tail -n2 | head -n1)
	delly-parallel call -t $TOOL -g $REF -o $target".build" `cat $prereq` &&
	mv $target".build" $target

tmp/Batch_clean%:Q: tmp/Batch%
##	set -x
	mkdir -p `dirname $target`
	cat $prereq | tr "\n" " " > $target".build" &&
	mv $target".build" $target

creaBatch:QV: 
##	set -x
	ls data/bams/*.bam > out.txt
	split -l $BATCH_N out.txt -a 2 -d Batch &&
	mv Batch* tmp/ &&
	rm out.txt
