< ../config.mk

all:VQ:
        bin/targets | xargs mk

results/TRA.merge.bcf:Q: data/test.bcf 
	mkdir -p $(dirname $target)
	delly-parallel merge -t TRA -m $MIN_LONG -n $MAX_LONG \
	-o $target.build -b 500 -r $OVERLAP data/test.bcf  \
	&& mv $target.build $target

