< ../config.mk

all:VQ:
        bin/targets | xargs mk

results/DUP.merge.bcf:Q: data/Batch00.bcf data/Batch01.bcf 
	mkdir -p $(dirname $target)
	delly-parallel merge -t DUP -m $MIN_LONG -n $MAX_LONG \
	-o $target.build -b 500 -r $OVERLAP data/Batch00.bcf data/Batch01.bcf  \
	&& mv $target.build $target

